import os
import json
import re
from datetime import datetime

out = []
def add(s): out.append(s)

add("# CheckDrive — Documentação Técnica\n")

add("## 1. Visão geral")
add("O CheckDrive é um sistema para gestão de frota e controle operacional, focado em checklists diários de veículos, controle de abastecimento, acompanhamento de manutenção preventiva/corretiva, gestão de motoristas, controle de inventário e gestão de empresas (multi-tenant).")
add("Ele permite que motoristas registrem condições dos veículos via checklists (com fotos), enquanto administradores visualizam relatórios e gerenciam as ocorrências em um dashboard. O sistema funciona como um PWA e inclui um modelo SaaS multi-tenant.")
add("\n---\n")

add("# 2. Stack tecnológica")
add("* **Frontend**: React (18+), TypeScript, Vite.")
add("* **Backend / Banco de dados**: Supabase (PostgreSQL).")
add("* **Autenticação**: Supabase Auth (E-mail/senha).")
add("* **Storage**: Supabase Storage (Buckets para fotos e assinaturas).")
add("* **Estilos**: Tailwind CSS, Lucide React (ícones).")
add("* **Roteamento**: React Router DOM (com suporte a rotas protegidas e baseadas em Role).")
add("* **Gráficos**: Recharts.")
add("* **Exportação de arquivos**: `xlsx` (Excel), `jspdf` / `jspdf-autotable` (PDF).")
add("* **Estado Local**: Hooks customizados, `AuthContext`.")
add("\n---\n")

add("# 3. Arquitetura do sistema")
add("```text\nUsuário (Motorista, Admin, Superadmin)\n   ↓\nFrontend (React PWA)\n   ↓\nAutenticação (Supabase Auth - JWT)\n   ↓\nBackend (PostgREST / Supabase API)\n   ↓\nBanco de dados (PostgreSQL com RLS - Row Level Security)\n   ↓\nStorage (Supabase Storage)\n```")
add("O frontend acessa diretamente o banco via chamadas na API do Supabase (`supabase-js`). A segurança é centralizada no banco utilizando Row Level Security (RLS) associado ao `auth.uid()` para filtrar acesso por Empresa (`company_id`).")
add("\n---\n")

add("# 4. Estrutura do projeto")
add("```text")
add("src/")
add("├── components/       # Componentes globais de layout e Auth (Guards, Layouts).")
add("├── contexts/         # Contextos Globais (AuthContext, AlertContext).")
add("├── hooks/            # Hooks Utilitários (usePersistentState).")
add("├── lib/              # Configurações do Supabase, utilitários globais, serviços.")
add("├── modules/          # Módulos segmentados do sistema (Arquitetura modular).")
add("│   ├── company/      # Dashboard Admin, gestão de frota, manutenção, inventário.")
add("│   ├── data_import/  # Funcionalidades de importação/exportação e relatórios customizados.")
add("│   ├── driver/       # Visão Mobile do motorista, checklists, painel de multas.")
add("│   ├── shared/       # Telas públicas (Landing, Login, Privacy).")
add("│   └── superadmin/   # Painel de gestão SaaS (Empresas, Planos, Auditoria Geral).")
add("├── pages/            # Páginas estáticas / antigas (algumas migrando para modules).")
add("├── routes/           # Orquestração principal de roteamento (`AppRoutes.tsx`).")
add("├── types.ts          # Tipagens TypeScript globais.")
add("└── utils/            # Utilitários gerais (formatadores, exportadores).")
add("```")
add("\n---\n")

add("# 5. Rotas e navegação")
add("| Rota | Página | Acesso | Função |")
add("| ---- | ------ | ------ | ------ |")
add("| `/` | Redirect | Público | Redireciona para `/login` |")
add("| `/login` | `Login` | Público | Autenticação de usuário |")
add("| `/quick-login` | `QuickLogin` | Público | Login simplificado |")
add("| `/reset-password` | `ResetPassword` | Público | Recuperação de senha |")
add("| `/privacy` | `Privacy` | Público | Política de privacidade |")
add("| `/driver/*` | `DriverRoutes` | `driver` | Área do motorista (Home, Checklists, Perfil, Abastecimento) |")
add("| `/admin/*` | `CompanyRoutes` | `admin`, `standard` | Gestão de Frota, Dashboard, Manutenção, Veículos |")
add("| `/sa/*` | `SuperAdminRoutes` | `superadmin` | Gestão de Tenants, Empresas, Auditoria, Planos SaaS |")
add("| `/relatorio-compartilhado/:id`| `SharedReportPage` | Público | View de relatórios externos compartilhados |")
add("\n---\n")

add("# 6. Autenticação")
add("* Baseada no **Supabase Auth** (`email` e `password`).")
add("* Sessão e estado do usuário persistidos e propagados via `<AuthProvider>` (`AuthContext`).")
add("* Rotas protegidas por Guards (`DriverGuard`, `CompanyGuard`, `SuperAdminGuard`, `ProtectedRoute`), que validam a `role` presente na tabela `profiles`.")
add("* Fluxo: Login via API Auth -> Retorna JWT -> `AuthContext` busca os dados adicionais em `profiles` -> Permite/Nega acesso ao layout correspondente.")
add("\n---\n")

add("# 7. Usuários e permissões")
add("* **Tipos (`role`)**:")
add("  * `superadmin`: Acesso total. Pode gerenciar empresas e planos SaaS.")
add("  * `admin`: Gestor da frota da Empresa (`company_id`). Visualiza e gerencia tudo dentro do Tenant.")
add("  * `standard`: Acesso gerencial limitado dentro do Tenant (conforme `visible_tabs`).")
add("  * `driver`: Acesso estrito ao módulo mobile (checklists, abastecimentos próprios).")
add("* **Permissões Refinadas**:")
add("  * O campo `visible_tabs` em `profiles` define quais abas do menu Admin o usuário `standard` pode ver (ex: `['vehicles', 'maintenance']`).")
add("* **RLS (Row Level Security)**: Usuários possuem `company_id`. Toda consulta no BD só retorna dados daquela empresa.")
add("\n---\n")

add("# 8. Módulos do sistema")

add("## 8.1 Company (Admin)")
add("* **Objetivo**: Gestão completa de frota da empresa.")
add("* **Páginas / Abas**: Dashboard, Veículos, Motoristas, Checklists Diários, Abastecimento, Manutenção, Histórico, Inventário/Estoque, Rotas, Fechamento de Pontuação, Auditoria.")
add("* **Permissões**: Role `admin` ou `standard`.")

add("## 8.2 Driver (Motorista)")
add("* **Objetivo**: Operação diária do motorista.")
add("* **Páginas**: Iniciar Checklist, Ver Meus Veículos, Painel de Pontuação, Lançar Abastecimentos.")
add("* **Permissões**: Role `driver`.")

add("## 8.3 Data Import (Relatórios)")
add("* **Objetivo**: Geração e exportação de dados analíticos.")
add("* **Páginas**: Operacional, Custos de Frota, Auditorias Customizadas.")

add("## 8.4 Superadmin")
add("* **Objetivo**: SaaS Master Dashboard.")
add("* **Páginas**: Empresas, Planos SaaS, Usuários Globais.")
add("\n---\n")

add("# 9. Dashboard")
add("* **Componente**: `CompanyDashboard` (`DashboardTab.tsx`).")
add("* **Cards Indicadores**: Total de Veículos, Veículos Disponíveis, Veículos em Manutenção, Checklists do Dia (Aprovados/Pendentes), Total Gasto no Mês (Abastecimento + Manutenção).")
add("* **Gráficos**: Uso de `recharts` para plotar Custos e Disponibilidade.")
add("* **Origem dos dados**: Tabelas `vehicles`, `alerts`, `checklist_submissions`, `vehicle_averages`.")
add("\n---\n")

add("# 10. Empresas")
add("* Cadastradas no módulo Superadmin (tabela `companies`).")
add("* Atributos: `id`, `name`, `cnpj`, `active`, `plan_id`, `max_users`, `max_vehicles`.")
add("* O isolamento de dados é 100% dependente da chave `company_id` inserida automaticamente via triggers no banco de dados e controlada via RLS.")
add("\n---\n")

add("# 11. Filiais")
add("* Encontrado como tabela subsidiária para organização espacial (`branches` / divisions).")
add("* **Campos**: Nome, CNPJ e vínculo com `company_id`.")
add("* Veículos e Motoristas podem ser vinculados a uma filial/rota.")
add("\n---\n")

add("# 12. Veículos")
add("* **Objetivo**: Cadastro e monitoramento da frota.")
add("* **Tabela**: `vehicles`.")
add("* **Campos Principais**: Placa (`plate`), Modelo (`model`), Tipo (`type`), ID do Modal (`modality_id`), `active`, `requires_trailer`.")
add("* **Fluxo**: Gestor cadastra veículo -> Motorista visualiza para fazer checklist.")
add("* Mantém cache/estado de Hodômetro (KM atualizada no último checklist).")
add("\n---\n")

add("# 13. Motoristas")
add("* Perfis com role `driver`. Armazenados na tabela `profiles`.")
add("* **Campos**: CPF, Nome, Tipo de Motorista (`Interno/Pátio`, `Rota`), Score, `participates_in_ranking`.")
add("* Vinculados indiretamente através de históricos de submissões de checklist.")
add("\n---\n")

add("# 14. Checklists")
add("* **Mecanismo Core** do app (Tabelas `checklist_submissions` e `checklist_answers`).")
add("* Motorista informa placa -> Hodômetro atual -> Responde itens (OK, NOK, N/A).")
add("* Se NOK, exige foto e observação (Storage).")
add("* O gestor vê no Admin, e se houver itens NOK, uma pendência (Issue) é gerada automaticamente no painel de Monitoramento.")
add("\n---\n")

add("# 15. Defeitos e pendências")
add("* Gerados automaticamente a partir de itens NOK no Checklist.")
add("* O Gestor acessa a aba de Ocorrências (Issues), define Status (Agendado, Resolvido), Responsável, Custo e Data de Resolução.")
add("* Resoluções compõem as métricas financeiras da frota.")
add("\n---\n")

add("# 16. Manutenção")
add("* **Aba**: `MaintenanceTab`.")
add("* **Controle**: Preventivas (Acompanhamentos por KM ou Data) e Corretivas (Alertas/Ocorrências).")
add("* Registros (`alerts`): Controlam o alerta de manutenção. Se for via KM, alerta dispara quando o Hodômetro atinge `last_km + interval_km`.")
add("* Foi recém adicionada uma funcionalidade de Exportar acompanhamentos (Excel) com os status 'Atrasada', 'Próxima do Vencimento' e 'Em dia'.")
add("\n---\n")

add("# 17. Abastecimento")
add("* **Aba**: `FuelTab` e tabela dedicada `vehicle_averages`.")
add("* Controla litros abastecidos, preço/litro, distância e km atual.")
add("* Calculo: `Média KM/L = Distância / Litros`.")
add("* Registros são lançados pelo motorista no fechamento/abastecimento ou pelo gestor manualmente.")
add("\n---\n")

add("# 18. Lava-jato")
add("> Não identificado como um módulo independente no código atual.")
add("\n---\n")

add("# 19. Relatórios")
add("* Centralizados em `ReportsOperationalView` no módulo `data_import`.")
add("* **Tipos**: Manutenções, Abastecimentos, Checklists, Cadastro de Veículos, Auditoria de Estoque.")
add("* **Exportações**: Suporta `.xlsx` (via biblioteca `xlsx`) e `.pdf` (via `jspdf`).")
add("\n---\n")

add("# 20. BI e indicadores")
add("* **Disponibilidade da frota**: `(Veículos Ativos - Veículos com status em manutenção) / Total * 100`.")
add("* **Custos Mensais**: Soma do campo custo das manutenções + abastecimentos.")
add("* **Indicador de Consumo Médio**: Soma das distâncias / Soma de litros no mês.")
add("\n---\n")

add("# 21. Banco de dados")
with open("documentation.md", "w", encoding="utf-8") as f:
    f.write("\n".join(out))
